---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bad-pods
  namespace: cronjob-test
roleRef:
  name: view
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: bad-pods
    namespace: cronjob-test
    kind: ServiceAccount

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bad-pods
  namespace: cronjob-test

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bad-pods
  namespace: cronjob-test
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: bad-pods
          containers:
          - name: bad-pods
            image: dockerhub.artifactory.davita.com/cwow-grafana/test-email-cronjob:3.1
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 25
          restartPolicy: OnFailure

