---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bad-pods
subjects:
- kind: ServiceAccount
  name: bad-pods
  namespace: kube-system
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bad-pods
  namespace: kube-system

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bad-pods
  namespace: cronjob-test
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: bad-pods
          containers:
          - name: bad-pods
            image: dockerhub.artifactory.davita.com/cwow-grafana/test-email-cronjob:1
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 25
          restartPolicy: OnFailure

