apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bad-pods
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          containers:
          - name: bad-pods
            image: dockerhub.artifactory.davita.com/cwow-grafana/test-email-cronjob:1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - ./sendmail.sh
          restartPolicy: OnFailure